### ISSUE TITLE
Implement In Offchain Worker

### ISSUE THREAD

**Issue by Supremesource** [agicommies/subspace-network#209]
# Tasks

## Implement Consensus Simulation for Irrational Copying Detection

Description:

We need to implement the `is_copying_irrational` function to determine if copying weights is irrational in the consensus simulation. The function is currently returning a placeholder `true` value and needs to be fully implemented.

Tasks:

1. [ ] Query onchain decrypted weights
2. [ ] Overwrite queried weights with `decrypted_weights` parameter
3. [ ] Query MeasuredStakeAmount
4. [ ] Query Minimum Delegation fee
5. [ ] Query onchain YumaParams
6. [ ] Generate weight copier information:
   - [ ] Calculate consensus_stake * MeasuredStakeAmount
   - [ ] Generate key
   - [ ] Get UID
   - [ ] Use last decrypted onchain weights
7. [ ] Append weight copier information to YumaParams
8. [ ] Run YumaEpoch with the new YumaParams
9. [ ] Update ConsensusSimulationResult struct
10. [ ] Implement and return `can_decrypt(ConsensusSimulationResult)`

Additional Notes:
- The function takes `netuid: u16` and `decrypted_weights: Vec<(u8, Vec<(u8, u8)>)>` as parameters
- The function is part of the `pallet_subspace::Config` trait implementation
