### ISSUE TITLE
Module curation DAO of subnet 0

### ISSUE THREAD

**Issue by Supremesource** [agicommies/subspace-network#40]
> This is the second part of a major Commune's incentives refactor (incentives v1).

This task should be worked on after resolving the issue https://github.com/agicommies/subspace-network/issues/39

# Task

This work is structured around a "legitimate" module (ss58 keys) list for the subnet `0`. 

## Storages
- [ ]  Add a new storage `legit_whitelist` that holds a list of ss58 keys.
- [ ]  Add a new global parameter (in the `global_params` struct) that holds a key `whitelist_nominator`.
- [ ]  Add new per-key state variable `multisig_abscence_count` that counts for every nominated multisig key the number of completed votes they did not participate in
- [ ]  Add new per-key state variable `multisig_participation_count` that counts for every nominated multisig key the number of completed votes they participate in

## Calls
- [ ]  Add a new call to the storage `legit_whitelist`, similar to the registration function, through this process keys can get “registered” to the whitelist. ONLY the `params.whitelist_nominator` can make changes to this `legit_whitelist`.
- [ ]  Add a new call to the storage `legit_whitelist` that deregisters keys from the whitelist
- [ ]  Add a new call through which new multisig keys can be added by `params.whitelist_nominator`
- [ ]  Add a new call through which existing multisig keys can be removed by `params.whitelist_nominator`

### Logic
> Note that this is "off-chain" logic (doesn't need any substrate modification, when tasks above are completed). 

The `whitelist_nominator` will be a multisignature of initially `12` keys, with keys being added/removed over time. Where the threshold for agreement should be dynamically `2/3` based on the number of nominated keys. This means that `2/3` of the nominated keys will have to agree to modify the whitelist or the list of nominated multisig keys.

This will likely require a custom implementation of a multisig that allows to add/remove keys through vote dynamically, without changing the multisig itself.

The whitelist will  be distributed to all validators on the subnet 0 as the "voting standard". With a UX-focused community validator build on top of this whitelist query. (This will be done in python).
